### ISSUE TITLE
Unable to knit thesis template: missing `insdljs.sty`

### ISSUE THREAD

**Issue by jtelliott** [Auburngrads/DODschools#4]
macOS 10.13.2
RStudio 1.0.153
pandoc 2.0.5
MacTeX-2017

Whenever I try to knit the template, I get the following:
 
```
--latex-engine has been removed. Use --pdf-engine instead.
Try pandoc --help for more information.
Error: pandoc document conversion failed with error 2
In addition: Warning message:
In as.POSIXlt.POSIXct(Sys.time()) :
                Unknown timezone ‘zone/tz/2017c.1.0/zoneinfo/America/New-York’
Execution halted
```

This seems to have been addressed by installing the most recent dev version of rmarkdown.
`devtools::install_github("rstudio/rmarkdown")`

However, new different issues have cropped up in the wake. I'm receiving these messages as knitting fails:

```
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': File changes, etc:
   Non-existent destination files:
      'Untitled.pdf'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -halt-on-error -interaction=batchmode -recorder  "Untitled.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets
===========Latexmk: Missing input file: 'insdljs.sty' from line
  '! LaTeX Error: File `insdljs.sty' not found.'
Latexmk: Missing input file: 'insdljs.sty' from line
  '! LaTeX Error: File `insdljs.sty' not found.'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'Untitled.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
! LaTeX Error: File `insdljs.sty' not found.

! Emergency stop.
<read *> 

Error: Failed to compile Untitled.tex. See Untitled.log for more info.
In addition: Warning message:
In as.POSIXlt.POSIXct(Sys.time()) :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/America/New_York'
Execution halted
```

**Comment by jtelliott** [comment]
Searching for `insdljs.sty` can lead you [here](https://ctan.org/pkg/insdljs?lang=en), where the package is supposedly stored.

However, trying all of the methods listed [here](https://tex.stackexchange.com/questions/12102/how-do-i-install-ctan-packages-on-mac-os-with-texshop) still doesn't help.

1. The TEX Live Utility manager doesn't have the `insdljs` package listed anywhere

2. Placing the package in the correct directory doesn't help, either. It actually seems that within the `insdljs` package, there is no `insdljs.sty` but rather a `.dtx`.

3. `tlgmr` can't find the appropriate package in the repository, command line just returns errors a "not found" error

**Comment by Auburngrads** [comment]
I don't think that this is an issue with the `insdljs.sty` package but rather an issue with `latexmk` - which always seems to be a problem.

Try the following:
1. open your package manager and remove the `latexmk` package
2. Search within your MacTex installation for the file `latexmk.exe` and delete it.
3. Try once again to knit the `.Rmd` file.

**Comment by jtelliott** [comment]
Neither the GUI package manager or command line will let me remove `latexmk`. The GUI (TEX Live Utility) just doesn't allow the option. Command line gives me this:

```
tlmgr: saving backups to /usr/local/texlive/2017/tlpkg/backups
tlmgr: not removing latexmk, needed by collection-binextra
tlmgr: not removing latexmk.x86_64-darwin, needed by latexmk
tlmgr: no packages removed.
tlmgr: action remove returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.
```

From what I've been able to find, `collection-binextra` doesn't have anything vital. Should I try removing it, as well?

Or I can try forcibly removing `latexmk`.

**Comment by Auburngrads** [comment]
Yes, find the`latexmk.exe` file and delete it. Mine was in the miktex/bin/64 directory.

**Comment by jtelliott** [comment]
Ran `sudo tlmgr remove --force latexmk` in bash, resulted in:

```
tlmgr: saving backups to /usr/local/texlive/2017/tlpkg/backups
tlmgr: latexmk is needed by collection-binextra
tlmgr: removing it anyway, due to --force
tlmgr: latexmk.x86_64-darwin is needed by latexmk
tlmgr: removing it anyway, due to --force
[1/1, ??:??/??:??] remove: latexmk
[2/1, 00:01/00:01] remove: latexmk.x86_64-darwin
tlmgr: ultimately removed these packages: latexmk latexmk.x86_64-darwin
running mktexlsr ...
done running mktexlsr.
running mtxrun --generate ...
done running mtxrun --generate.
tlmgr: package log updated: /usr/local/texlive/2017/texmf-var/web2c/tlmgr.log
```

Then I went in and even deleted the backups. Unfortunately, trying to knit gave me:

```
! LaTeX Error: File `insdljs.sty' not found.

! Emergency stop.
<read *> 
```

So, the error message is shorter this time - that's something, I guess. Here's the log file, if it helps.

[Untitled.log](https://github.com/Auburngrads/DODschools/files/1568663/Untitled.log)

**Comment by Auburngrads** [comment]
Are you at AFIT today or tomorrow?  If so, come by my office.

I extracted insdljs.sty from the .dtx file and loaded it into my copy of the package.  This gave me a number of warnings that I tracked back to interference between functions in the insdljs and eforms packages.  I don't think that these packages are supposed to be used together - which is why I don't think its an issue with insdljs, but I could be wrong.
________________________________

**Comment by jtelliott** [comment]
I'm here. Where is your office?

**Comment by Auburngrads** [comment]
Bldg 640 Rm 205
________________________________

**Comment by jtelliott** [comment]
Oh, also - not sure if removing  `latexmk` was necessary? But either way, things are working fine without it.

**Comment by Auburngrads** [comment]
Updated package with [__this commit__](https://github.com/Auburngrads/DODschools/commit/1ab628f792535261826217f812e500d3e8066416) to include entire Acrotex bundle. 

Thesis compiled successfully on both Windows and Mac
