### ISSUE TITLE
Numbered citations

### ISSUE THREAD

**Issue by jrlindell** [Auburngrads/DODschools#6]
When using numbered citations, the numbers go in reference to the bibliography order rather than the other way around. For example, if there are three citations; Allen, Barry, and Smith. If I reference Smith first, Smith should be given the number 1, and the bibliography should change accordingly. For now, Smith would be referenced as 3.

**Comment by Auburngrads** [comment]
@jrlindell 

I updated the TeX template for the AFIT thesis such that if the YAML tag in the metadata.yml file for `numeric_citations` is set to true (or yes) `\bibliographystyle{unsrtnat}` is used.  If `numeric_citations` is false (or no) `\bibliographystyle{abbrvnat}` is used.

In my testing, this seems to have fixed the problem.

## What you need to do to implement this fix

1. reinstall the DODschools package to get the updated template `devtools::install_github('Auburngrads/DODschools)` 
2. Add the following line to the YAML header in your master .Rmd file  __(You don't need to change the metadata.yml file)__ 

```
num_cite:   "`r DODschools::noTouch('metadata.yml')$num_cite`"
``` 
You should preferably add this line just above the line that reads `output:`

After following these steps, try to recompile the document and let me know whether or not this fixes your issue
